### ISSUE TITLE
Promise isFulfilled when webhook fails

### ISSUE THREAD

**Issue by eredi93** [simplabs/ember-cli-deploy-webhooks#17]
On my deploy the webhook is crucial and an error on the webhook should make the Promise to fail.
How is that possible that the promise is ful filled on a webhook error?
Can we get a callback passed to the request object?

**Comment by LevelbossMike** [comment]
This is actually expected behaviour because we figured that a failed webhook notification shouldn't fail the whole deployment as an external 3rd party service may be down. 

What are you using the webhook for that should result in a failed deploy? Most often one would call a webhook after a deploy has finished (i.e. a new revision was activated) thus the failure wouldn't stop/revert the deployment.

We could of course make this configurable but you'd need to implement a deploy cleanup on `didFail`. Interested to hear more about your use-case and your thoughts on this.

**Comment by eredi93** [comment]
First of all thanks for getting back to me.
My deploy process in summary is:
- build
- upload to s3
- call the web app and tell to use the new ember app (the web hook)

If the web hook fail I want to have the deploy to fail so it will result as failed deploy on CI. Right now a webhook failure would make the main app not use the new ember app and it could create confusion.
For my use case I shouldn't need to clean up on didFail as in CI each deployment is isolated and in case of failure it would restart from scratch.

I understand that this is the expected behaviour but I'd like to have the opportunity to make the deploy fail. An option could be passing an option itMustPass: true and that would make the Promise to fail.

What do you think is the best thing to do? I'd love to have this feature in the plugin.

**Comment by LevelbossMike** [comment]
We can indeed add a property `willFailDeploy` or something called like that and make this configurable. I won't have time to look into this in the next few days. Would you be interested in creating a PR for this?

**Comment by eredi93** [comment]
cool! i'll make a PR next week 😄

**Comment by LevelbossMike** [comment]
fixed by #19

**Comment by eredi93** [comment]
Thanks for merging the PR.
Was wondering when it will be available in a release so i can update my project.

**Comment by LevelbossMike** [comment]
@marcoow can you cut a release please? Would be great to have the last to additions released on npm.

**Comment by marcoow** [comment]
I'll publish a new release tomorrow

**Comment by eredi93** [comment]
Thank you
